name: OpenCue Release Blog Post

# Workflow to automate the creation of a blog post for an OpenCue release.
#
# This workflow is triggered externally via the `workflow_dispatch` event sent via the
# GitHub REST API.
#
# It can be triggered manually by sending an HTTP request:
#   $ curl \
#       -X POST
#       -H "Accept: application/vnd.github.v3+json" \
#       -H "Content-Type: application/json" \
#       https://${GITHUB_PAT}@api.github.com/repos/AcademySoftwareFoundation/opencue.io/actions/workflows/2618928/dispatches \
#       --data '{"ref": "master", "inputs": {"release_version": "vX.X.X"}}'
#
# The main OpenCue release pipeline uses this to trigger a new blog post when
# the release is created on the main code repository.

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'OpenCue release version for which a blog post will be created'
        required: true

jobs:
  create_blog_post:
    runs-on: ubuntu-latest
    name: Create Blog Post
    env:
      REPO_ROOT: /repos/AcademySoftwareFoundation/OpenCue
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print release version
        run: echo "Creating blog post for release ${{ github.event.inputs.release_version }}"
      - name: Generate blog post
        env:
          GITHUB_PAT: ${{ secrets.OPENCUE_AUTO_PAT }}
        run: |
          set -e

          tag_name=${{ github.event.inputs.release_version }}
          release_url="https://${GITHUB_PAT}@api.github.com${REPO_ROOT}/releases/tags/${tag_name}
          changelist=$(curl -s -L ${release_url} | jq '.body' | sed 's/.*## Changes://')

          echo ${changelist}
