name: OpenCue Release Blog Post

# Workflow to automate the creation of a blog post for an OpenCue release.
#
# This workflow is triggered externally via the `workflow_dispatch` event sent via the
# GitHub REST API.
#
# It can be triggered manually by sending an HTTP request:
#   $ curl \
#       -X POST
#       -H "Accept: application/vnd.github.v3+json" \
#       -H "Content-Type: application/json" \
#       https://${GITHUB_PAT}@api.github.com/repos/AcademySoftwareFoundation/opencue.io/actions/workflows/2618928/dispatches \
#       --data '{"ref": "master", "inputs": {"release_version": "vX.X.X"}}'
#
# The main OpenCue release pipeline uses this to trigger a new blog post when
# the release is created on the main code repository.

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'OpenCue release version for which a blog post will be created'
        required: true

jobs:
  create_blog_post:
    runs-on: ubuntu-latest
    name: Create Blog Post
    env:
      MAIN_REPO: AcademySoftwareFoundation/OpenCue
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print release version
        run: echo "Creating blog post for release ${{ github.event.inputs.release_version }}"
      - name: Generate blog post
        env:
          GITHUB_PAT: ${{ secrets.OPENCUE_AUTO_PAT }}
        run: |
          set -e

          tag_name="${{ github.event.inputs.release_version }}"
          repo_root="https://${GITHUB_PAT}@api.github.com/repos/AcademySoftwareFoundation/OpenCue"
          release_url="${repo_root}/releases/tags/${tag_name}"

          release_date="$(curl -s -L ${release_url} | jq -r '.published_at' | sed 's/T[0-9:]\+Z//')"

          # What's going on here:
          # 1. We fetch the GitHub release data via the GitHub REST API
          # 2. We use the `jq` JSON parser to get only the body text.
          # 3. Pre-filter the body text for only the changelist lines.
          # 4. Remove the leading commit hashes, they aren't useful outside of a GitHub context.
          # 5. Turn Pull Request numbers into links to the PRs themselves.
          changelist="$(curl -s -L ${release_url} \
            | jq -r '.body' \
            | egrep '^\* ([a-f0-9]+) ' \
            | sed 's/[a-f0-9]\{40\}/ /' \
            | sed 's/(#\([0-9]\+\))/[#\1](https:\/\/github.com\/AcademySoftwareFoundation\/OpenCue\/pull\/\1)/g')"

          cat <<BLOG_POST_CONTENTS >> foo.txt
          ---
          title: "Announcing the release of OpenCue ${tag_name}"
          linkTitle: "${tag_name} release"
          date: ${release_date}
          description: "OpenCue ${tag_name} release notes"
          ---

          [${tag_name} of OpenCue](https://github.com/AcademySoftwareFoundation/OpenCue/releases/tag/${tag_name})
          includes the following changes and updates:

          ${changelist}
          BLOG_POST_CONTENTS

          cat foo.txt
